[package]
name = "gw-polyjuice-sender-recover"
version = "1.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
gw-common = { path = "../common" }
gw-generator = { path = "../generator" }
gw-traits = { path = "../traits" }
gw-types = { path = "../types" }
gw-utils = { path = "../utils" }
gw-store = { path = "../store" }
log = "0.4"
thiserror = "1.0"
tracing = { version = "0.1", features = ["attributes"] }
