version = "0.4.4"
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"
toolchain = "nightly-2020-09-28"

[[contracts]]
name = "state-validator"
template_type = "Rust"

[[contracts]]
name = "deposition-lock"
template_type = "Rust"

[[contracts]]
name = "custodian-lock"
template_type = "Rust"

[[contracts]]
name = "withdrawal-lock"
template_type = "Rust"

[[contracts]]
name = "challenge-lock"
template_type = "Rust"

[[contracts]]
name = "stake-lock"
template_type = "Rust"

[[contracts]]
name = "always-success"
template_type = "Rust"

