[package]
name = "gw-jsonrpc-types"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
faster-hex = "0.4"
gw-types = { path = "../types" }
gw-chain = { path = "../chain" }
gw-generator = { path = "../generator" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
ckb-types = "0.37.0"
ckb-jsonrpc-types = "0.37.0"
failure = "0.1.5"

