[package]
name = "gw-web3-rpc-client"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ckb-jsonrpc-types = "0.105.1"
ckb-types = "0.105.1"
gw-types = { path = "../../../gwos/crates/types" }
gw-common = { path = "../../../gwos/crates/common" }
gw-jsonrpc-types = { path = "../../../crates/jsonrpc-types" }
jsonrpc-core = "18"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
async-jsonrpc-client = { version = "0.3.0", default-features = false, features = ["http-async-std"] }
async-std = "1.12.0"
log = "0.4"
itertools = "0.10.3"
