[package]
name = "gw-common"
version = "1.8.0-rc2"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1"
merkle-cbt = { version = "0.3.0", default-features = false }
thiserror = { version = "1.0", optional = true }
gw-hash = { path = "../hash", default-features = false }
gw-types = { path = "../types", default-features = false }

[features]
default = ["std"]
std = ["thiserror", "gw-types/std"]
