[package]
name = "gw-utils"
version = "1.8.0-rc3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../../gwos/crates/types" }
gw-config = { path = "../config" }
gw-common = { path = "../../gwos/crates/common" }
gw-smt = { path = "../smt" }
gw-rpc-client = { path = "../rpc-client" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
gw-store = { path = "../store" }
anyhow = "1.0"
faster-hex = "0.4"
ckb-crypto = "0.105.1"
sha3 = "0.10.6"
secp256k1 = "0.24"
log = "0.4"
rand = { version = "0.8.5", features = ["min_const_gen"] }
ckb-types = "0.105.1"
tokio = "1"
zstd = "0.11.2"
ethabi = { version = "18.0.0", default-features = false, features = ["thiserror", "std"] }
hex-literal = "0.3.4"
