[package]
name = "gw-mem-pool"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../types" }
gw-common = { path = "../common" }
gw-challenge = { path = "../challenge" }
gw-generator = { path = "../generator" }
gw-store = { path = "../store" }
gw-traits = { path = "../traits" }
gw-rpc-client = { path = "../rpc-client" }
gw-poa = { path = "../poa" }
gw-config = { path = "../config" }
gw-utils = { path = "../utils" }
gw-runtime = { path = "../runtime" }
rdkafka = { version = "0.25", default-features = false }
gw-rpc-ws-server = { path = "../rpc-ws-server" }
tokio = "1.15"
anyhow = "1.0"
log = "0.4"
hex = "0.4"

[dev-dependencies]
tempfile = "3.2"
