[package]
name = "gw-tx-filter"
version = "1.8.0-rc3"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common = { path = "../../gwos/crates/common" }
gw-smt = { path = "../smt" }
gw-config = { path = "../config" }
gw-traits = { path = "../traits" }
gw-types = { path = "../../gwos/crates/types" }
thiserror = "1.0"
log = "0.4"
hex = "0.4"
