[package]
name = "gw-ckb-hardfork"
version = "1.7.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
tokio = "1.15"
ckb-types = "0.104.0"
arc-swap = "1.5"
