[package]
name = "gw-tools"
version = "1.8.0-rc3"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
clap = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
toml_edit = { version = "0.17.1", features = ["easy", "serde"] }
tempfile = "3.1"
lazy_static = "1.4"
secp256k1 = "0.24"
sha3 = "0.10.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ckb-jsonrpc-types = "0.105.1"
ckb-types = "0.105.1"
ckb-resource = "0.105.1"
ckb-hash = "0.105.1"
ckb-fixed-hash = "0.105.1"
ckb-crypto = "0.105.1"
ckb-traits = "0.105.1"
ckb-dao-utils = "0.105.1"
gw-types = { path = "../../gwos/crates/types" }
gw-config = { path = "../config" }
gw-common = { path = "../../gwos/crates/common" }
gw-generator = { path = "../generator" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
gw-utils = { path = "../utils" }
gw-rpc-client = { path = "../rpc-client" }
gw-version = { path = "../version" }
gw-builtin-binaries = { path = "../builtin-binaries" }
url = { version = "2.2", features = ["serde"] }
faster-hex = "0.5.0"
rand = "0.8"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
jsonrpc-core = "18"
csv = "1.1.6"
bech32 = "0.8.1"
tracing-subscriber = { version = "0.3.11", default-features = false, features = ["tracing-log", "env-filter", "fmt"] }
parking_lot = "0.12"

[dev-dependencies]
ckb-chain-spec = "0.105.1"
ckb-script = "0.105.1"
ckb-mock-tx-types = "0.105.1"
