[package]
name = "gw-common"
version = "0.1.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1"
sparse-merkle-tree = { version = "0.3.1-pre", default-features = false }
gw-hash = { path = "../hash" }

[features]
default = ["std"]
std = ["sparse-merkle-tree/std"]
