[workspace]
members = [
  "custodian-lock",
  "deposition-lock",
  "withdrawal-lock",
  "challenge-lock",
  "stake-lock",
  "state-validator",
  "validator-utils",
  "always-success",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 's'
overflow-checks = true
panic = 'abort'
