[package]
name = "godwoken-api"
version = "0.1.0"
authors = ["hupeng <bitrocks.hu@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "godwoken_api"
crate-type = ["cdylib"]
test = false

[build-dependencies]
neon-build = "0.5.0"

[dependencies]
gw-chain = { path = "../../../crates/chain" }
gw-common = { path = "../../../crates/common" }
gw-generator = { path = "../../../crates/generator" }
gw-types = { path = "../../../crates/types" }
gw-config = { path = "../../../crates/config" }
gw-db = { path = "../../../crates/db" }
gw-store = { path = "../../../crates/store" }
gw-traits = { path = "../../../crates/traits" }
gw-jsonrpc-types= { path = "../../../crates/jsonrpc-types" }
ckb-fixed-hash = "0.37.0"
anyhow = "1.0"
serde_json = "1.0"
parking_lot = "0.11"
toml = "0.5"
neon = "0.5.0"
godwoken-polyjuice = "0.0.6"
