[package]
name = "gw-types"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = ["molecule/std", "sparse-merkle-tree/std", "ckb-fixed-hash", "ckb-types"]

[dependencies]
molecule = { version = "0.7.1", default-features = false }
cfg-if = "0.1"
gw-hash = { path = "../hash", default-features = false }
ckb-fixed-hash = { version = "0.100.0-rc2", optional = true }
sparse-merkle-tree = { version = "0.5.2-rc1", default-features = false }
ckb-types = { version = "0.100.0-rc2", default-features = false, optional = true }
