[package]
name = "c-uint256-tests"
version = "1.8.0-rc2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2"

[dev-dependencies]
proptest = "1.0"
primitive-types = { version = "0.12", default-features = false, features = [ "impl-serde", "impl-rlp" ] }

[build-dependencies]
cc = "1.0"
