[package]
name = "gw-state"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-utils = { path = "../gw-utils" }
ckb-smt = { path = "../ckb-smt", default-features = false }
