[package]
name = "gw-store"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-db = { path = "../db" }
gw-types = { path = "../types" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
anyhow = "1.0"
thiserror = "1.0"
parking_lot = "0.11"
