[package]
name = "gw-store"
version = "1.8.0-rc3"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../../gwos/crates/types" }
gw-config = { path = "../config" }
gw-common = { path = "../../gwos/crates/common" }
gw-traits = { path = "../traits" }
gw-smt = { path = "../smt" }
anyhow = "1.0"
arc-swap = "1.5.0"
log = "0.4"
im = "15.1.0"
autorocks = { path = "../autorocks" }
tempfile = "3.3.0"
serde = "1.0.149"

[features]
smt-trie = ["gw-smt/smt-trie"]
