[package]
name = "gw-store"
version = "1.7.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-db = { path = "../db" }
gw-types = { path = "../types" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
gw-traits = { path = "../traits" }
anyhow = "1.0"
thiserror = "1.0"
arc-swap = "1.5.0"
log = "0.4"
im = "15.1.0"
