[package]
name = "gw-otel"
version = "1.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
faster-hex = "0.6"
once_cell = "1.15"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-http = "0.7"
prometheus-client = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"]}
thiserror = "1.0"
# For latest tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-appender = "0.2"
tracing-opentelemetry = "0.18"
tracing-serde = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "parking_lot", "smallvec", "tracing-log", "json"] }
