[package]
name = "gw-rpc-client"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common = { path = "../common" }
gw-config = { path = "../config" }
gw-types = { path = "../types" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
faster-hex = "0.4"
ckb-crypto = "0.100.0"
ckb-fixed-hash = "0.100.0"
ckb-types = "0.100.0"
toml = "0.5"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-channel = "1.4.2"
async-jsonrpc-client = { version = "0.3.0", default-features = false, features = ["http-tokio"] }
env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
serde_json = "1.0"
tokio = "1.15"
lazy_static = "1.4"
hex = "0.4"
async-trait = "0.1"
semver = "1.0"
rand = "0.8"
arc-swap = "1.5"
thiserror = "1.0"
