[package]
name = "gw-rpc-client"
version = "1.8.0-rc3"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common = { path = "../../gwos/crates/common" }
gw-config = { path = "../config" }
gw-types = { path = "../../gwos/crates/types" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
ckb-fixed-hash = "0.105.1"
ckb-types = "0.105.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-jsonrpc-client = { version = "0.3.0", default-features = false, features = ["http-tokio"] }
log = "0.4.14"
serde_json = "1.0"
tokio = "1"
async-trait = "0.1"
rand = "0.8"
arc-swap = "1.5"
thiserror = "1.0"
tracing = { version = "0.1", features = ["attributes"] }
