# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Init submodules
      run: git submodule init && git submodule update -r && cd c/deps/ckb-miscellaneous-scripts/ && git submodule init && git submodule update -r
    - name: Install Rust components
      run: rustup component add rustfmt
    - name: Install moleculec
      run: cargo install moleculec --version 0.6.1
    - name: Install neon-cli
      run: npm install -g neon-cli
    - name: Compile C contracts dependencies
      run: cd c/deps/ckb-miscellaneous-scripts && make all-via-docker
    - name: Compile C contracts
      run: cd c && make
    - name: Install packages
      run: yarn
    - name: Check format
      run: yarn workspaces run fmt && git diff --exit-code
    - name: Build native modules
      run: cd packages/godwoken; neon build; cd ../..
    - name: Build tools
      run: yarn workspace @ckb-godwoken/tools tsc
    - name: Build runner
      run: yarn workspace @ckb-godwoken/runner tsc
